apiVersion: v1
kind: Pod
metadata:
  name: stop-before-pod1
  labels:
    app: stop-before
spec:
  restartPolicy: Never
  containers:
    - name: kuber-seminar
      image: blockjjam/kuber-seminar:latest
      ports:
        - containerPort: 8021
          name: http-web-svc
---
apiVersion: v1
kind: Pod
metadata:
  name: stop-before-pod2
  labels:
    app: stop-before
spec:
  restartPolicy: Never
  containers:
    - name: kuber-seminar
      image: blockjjam/kuber-seminar:latest
      ports:
        - containerPort: 8021
          name: http-web-svc

---
apiVersion: v1
kind: Service
metadata:
  name: stop-before
spec:
  selector:
    app: stop-before
  ports:
    - name: name-of-service-port
      protocol: TCP
      port: 8020
      targetPort: http-web-svc