apiVersion: v1
kind: Pod
metadata:
  name: stop-after-pod1
  labels:
    app: stop-after
spec:
  containers:
    - name: kuber-seminar
      image: blockjjam/kuber-seminar:latest
      livenessProbe:
        httpGet:
          path: /actuator/health/liveness
          port: 8021
        initialDelaySeconds: 20
        periodSeconds: 20
      ports:
        - containerPort: 8021
          name: http-web-svc
---
apiVersion: v1
kind: Pod
metadata:
  name: stop-after-pod2
  labels:
    app: stop-after
spec:
  containers:
    - name: kuber-seminar
      image: blockjjam/kuber-seminar:latest
      livenessProbe:
        httpGet:
          path: /actuator/health/liveness
          port: 8021
        initialDelaySeconds: 20
        periodSeconds: 20
      ports:
        - containerPort: 8021
          name: http-web-svc

---
apiVersion: v1
kind: Service
metadata:
  name: stop-after
spec:
  selector:
    app: stop-after
  ports:
    - name: name-of-service-port
      protocol: TCP
      port: 8021
      targetPort: http-web-svc