apiVersion: v1
kind: Pod
metadata:
  name: scale-before-pod1
  labels:
    app: scale-before
spec:
  restartPolicy: Never
  containers:
    - name: kuber-seminar
      image: blockjjam/kuber-seminar:latest
      ports:
        - containerPort: 8021
          name: http-web-svc
---
apiVersion: v1
kind: Pod
metadata:
  name: scale-before-pod2
  labels:
    app: scale-before
spec:
  restartPolicy: Never
  containers:
    - name: kuber-seminar
      image: blockjjam/kuber-seminar:latest
      ports:
        - containerPort: 8021
          name: http-web-svc

---
apiVersion: v1
kind: Service
metadata:
  name: scale-before
spec:
  selector:
    app: scale-before
  ports:
    - name: name-of-service-port
      protocol: TCP
      port: 8022
      targetPort: http-web-svc